<?xml version="1.0" encoding="UTF-8"?><testrun name="SquareTest" project="Square" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="SquarePackage.SquareTest" time="0.013" displayname="SquareTest" uniqueid="[engine:junit-vintage]/[runner:SquarePackage.SquareTest]">
    <testcase name="shouldWorkForSomeExamples" classname="SquarePackage.SquareTest" time="0.013" displayname="shouldWorkForSomeExamples" uniqueid="[engine:junit-vintage]/[runner:SquarePackage.SquareTest]/[test:shouldWorkForSomeExamples(SquarePackage.SquareTest)]">
      <failure>java.lang.AssertionError: 3 isn't a square number expected:&lt;false&gt; but was:&lt;true&gt;&#13;
	at org.junit.Assert.fail(Assert.java:89)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:835)&#13;
	at org.junit.Assert.assertEquals(Assert.java:120)&#13;
	at SquarePackage.SquareTest.shouldWorkForSomeExamples(SquareTest.java:12)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
